# You have to run Perception first to populate objects
# Then choose a object to grasp
int32 object_index #index of object to grasp

bool sample_cloud_from_obb #if true, generate a pointcloud from the obbs instead of using the sensor cloud
# So GDP will try to grasp the bounding box

bool disable_top_grasp #copies plane cloud above the object
# so GPD thinks there is a ceiling

float32 min_distance_to_plane #minimum distance the gripper should have to the plane
# internally the plane is offsetted by this value (so GPD thinks the plane is higher)

int32 num_grasps_selected #number of selected grasps (sorted by score)

# Filtering of candidates based on their approach direction
# direction to compare against
geometry_msgs/Point approach_direction # 1/0/0 by default
# angle in degree above which grasps are filtered
float32 thresh_deg #disable if 0.0


float32 pre_grasp_dist #distance from pre_grasp to grasp in approach direction
float32 retreat_dist #distance in plane normal direction to retreat after grasp
---

# Response
bool success
string message

Grasp[] grasps