simple_grasping:
  ros__parameters:
    common:
      frame_id: "base_footprint" #z axis must be upwards
      # and it is easier if floor is at z=0
      grasp_frame_id: "gripper_grasping_frame"
      n_threads: 8
      debug: True
      gpd_cfg_file: "/root/ros2_ws/src/simple_grasping/params/gpd.cfg"
    filter:
      voxel_size: 0.005 #0.0 to disable
      radius: 0.05
      min_points: 3 # 0 to disable
      workspace: #crop cloud
        x_min: 0.0
        x_max: 2.0
        y_min: -1.5
        y_max: 1.5
        z_min: 0.05 #no floor
        z_max: 2.0
    plane_detection:
      normal_estimation_radius: 0.05
      horizontal_threshold: 10.0 # degree
      clustering_tolerance: 0.05
      clustering_min_cluster_size: 20
      clustering_max_cluster_size: 1000000
      min_area: 0.1
      plane_thickness: 0.02
      ransac_iterations: 100
    object_detection:
      clustering_tolerance: 0.025
      clustering_min_cluster_size: 10
      clustering_max_cluster_size: 10000
