services:
  simple_grasping:
    container_name: simple_grasping
    image: simple_grasping
    build:
      context: ..
      dockerfile: docker/Dockerfile
    runtime: nvidia
    environment:
      ROS_DOMAIN_ID: 42
      DISPLAY: $DISPLAY
      QT_X11_NO_MITSHM: "1"
      NVIDIA_VISIBLE_DEVICES: all
      NVIDI_DRIVER_CAPABILITIES: compute,video,utility,graphics
      LIBGL_ALWAYS_SOFTWARE: "1"
    network_mode: host
    ipc: host
    privileged: true
    stdin_open: true
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - $HOME/.Xauthority:/root/.Xauthority
      - ../simple_grasping/params:/root/ros2_ws/src/simple_grasping/params
    command: ros2 launch simple_grasping simple_grasping.launch.py input_cloud_topic:=/head_front_camera/depth_registered/points

  test:
    container_name: test
    extends: simple_grasping
    command: 
      - bash
      - -c
      - |
          sleep 1
          ros2 service call /simple_grasping/start_perception simple_grasping_interfaces/srv/StartPerception "querry_point:
            x: 0.0
            y: 0.0
            z: 0.0
          sort_planes_by_height: true
          height_above_plane: 0.35
          width_adjustment: -0.05
          return_cloud: false" 

          ros2 service call /simple_grasping/generate_grasps simple_grasping_interfaces/srv/GenerateGrasps "object_index: 0
          sample_cloud_from_obb: true
          disable_top_grasp: true
          min_distance_to_plane: 0.03
          num_grasps_selected: 5
          approach_direction:
            x: 1.0
            y: 0.0
            z: 0.0
          thresh_rad: 1.0
          pre_grasp_dist: 0.15
          retreat_dist: 0.05" 
